<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/array_utils_module?artifactURI=file:/C:/00_AXELSI/20_src/100_composer_ws/array_utils/Artifacts/Modules/array_utils_module.module" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="array_utils_module" contact_info="Ingemar Axelsson" a_module_type="[Standard Module]">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/array_utils_interface?artifactURI=file:/C:/00_AXELSI/20_src/100_composer_ws/array_utils/Artifacts/JAR%20Definitions/array_utils_interface.jardef#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/array_utils_implementation?artifactURI=file:/C:/00_AXELSI/20_src/100_composer_ws/array_utils/Artifacts/JAR%20Definitions/array_utils_implementation.jardef#//@dataModel"/>
    <javadocs href="urn:com.emc.ide.artifact.sysobjectsubtype/array_utils_javadoc.zip?artifactURI=file:/C:/00_AXELSI/20_src/100_composer_ws/array_utils/Artifacts/SysObjects/array_utils_javadoc.zip.sysobject#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="com.emc.ps.bpm.arrayutils.impl.ArrayUtilsImpl">
      <a_interfaces>com.emc.ps.bpm.arrayutils.ArrayUtils</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
    </primaryElement>
    <miscellaneous objectName="Miscellaneous">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
